CREATE TABLE AIRPORTS(
	Id INTEGER NOT NULL,
	Ident VARCHAR(4) NOT NULL,
	Type VARCHAR(20) NOT NULL,
	Name VARCHAR(100) NOT NULL,
	LatDeg FLOAT NOT NULL,
	LongDeg FLOAT NOT NULL,
	ElevFt INTEGER,
	Continent VARCHAR(3),
	ISOCountry VARCHAR(3),
	ISORegion VARCHAR(10),
	City VARCHAR(100),
	Scheduled_service VARCHAR(3) NOT NULL,
	GPSCode VARCHAR(10),
	IATACode VARCHAR(10),
	LocalCode VARCHAR(10),
	HomeLink VARCHAR(200),
	WikipediaLink VARCHAR(2083),
	Keyword VARCHAR(500),
	
	CONSTRAINT pk_airport PRIMARY KEY(Id)
);

CREATE TABLE COUNTRIES(
	Id INTEGER NOT NULL,
	Code VARCHAR(2),
	Name VARCHAR(50) NOT NULL,
	Continent VARCHAR(2),
	WikipediaLink VARCHAR(2083),
	Keywords VARCHAR(500),
	
	CONSTRAINT pk_countries PRIMARY KEY(Id)
);

CREATE TABLE GEOCITIES15K(
	GeonameID INTEGER NOT NULL,
	Name VARCHAR(200) NOT NULL,
	AsciiName VARCHAR(200) NOT NULL,
	AlternateNames TEXT,
	Lat FLOAT NOT NULL,
	Long FLOAT NOT NULL,
	FeatureClass VARCHAR(5) NOT NULL, --talvez varchar 1
	FeatureCode VARCHAR(5) NOT NULL,
	Country VARCHAR(5) NOT NULL,
	CC2 VARCHAR(5),
	Admin1Code VARCHAR(50),
	Admin2Code VARCHAR(50),
	Admin3Code VARCHAR(50),
	Admin4Code VARCHAR(50),
	Population INTEGER NOT NULL,
	Elevation INTEGER,
	Dem INTEGER,
	TimeZone VARCHAR(50) NOT NULL,
	Modification DATE,
	
	CONSTRAINT pk_geocities PRIMARY KEY(GeonameID)
);

CREATE TABLE Status(
	StatusId INTEGER NOT NULL,
	Status VARCHAR(50) NOT NULL,

	CONSTRAINT pk_status PRIMARY KEY(StatusId)
);

CREATE TABLE Seasons(
	Year VARCHAR(4) NOT NULL,
	URL VARCHAR(2048),

	CONSTRAINT pk_seasons PRIMARY KEY(Year)
);

CREATE TABLE Circuits(
	CircuitID INTEGER NOT NULL,
	CircuitRef VARCHAR(100) NOT NULL,
	Name VARCHAR(100) NOT NULL,
	Location VARCHAR(100) NOT NULL,
	Country VARCHAR(100) NOT NULL,
	Lat FLOAT NOT NULL,
	Lng FLOAT NOT NULL,
	Alt VARCHAR(10) DEFAULT '\N' NOT NULL,
	URL VARCHAR(2048) NOT NULL,

	CONSTRAINT pk_circuits PRIMARY KEY(CircuitID)
);

CREATE TABLE Constructors(
	ConstructorID INTEGER NOT NULL,
	ConstructorRef VARCHAR(50) NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Nationality VARCHAR(50) NOT NULL,
	URL VARCHAR(2048) NOT NULL,

	CONSTRAINT pk_constructors PRIMARY KEY(ConstructorID)
);

CREATE TABLE Driver(
	DriverId INTEGER NOT NULL,
	DriverRef VARCHAR(50) NOT NULL,
	Number VARCHAR(5) DEFAULT '\N' NOT NULL,
	Code VARCHAR(3) DEFAULT '\N' NOT NULL,
	Forename VARCHAR(50) NOT NULL,
	Surname VARCHAR(50) NOT NULL,
	DateOfBirth DATE NOT NULL,
	Nationality VARCHAR(50) NOT NULL,
	URL VARCHAR(2048) NOT NULL,

	CONSTRAINT pk_driver PRIMARY KEY(DriverId)
);

CREATE TABLE Races(
	RaceId INTEGER NOT NULL,
	Year VARCHAR(4) NOT NULL,
	Round INTEGER NOT NULL,
	CircuitId INTEGER NOT NULL,
	Name VARCHAR(100) NOT NULL,
	Date DATE NOT NULL,
	Time VARCHAR(20) DEFAULT '/N',
	URL VARCHAR(2048) NOT NULL,

	CONSTRAINT pk_races PRIMARY KEY(RaceId),
	CONSTRAINT fk_race_year FOREIGN KEY(Year) REFERENCES Seasons(Year)
);

CREATE TABLE Laptimes(
	RaceId INTEGER NOT NULL,
	DriverId INTEGER NOT NULL,
	Lap INTEGER NOT NULL,
	Position INTEGER NOT NULL,
	Time TIME NOT NULL,
	Milliseconds INTEGER NOT NULL,

	CONSTRAINT pk_laptime PRIMARY KEY(RaceId, DriverId, Lap),
	CONSTRAINT fk_laptime_race FOREIGN KEY(RaceId) REFERENCES Races(RaceId)
);

CREATE TABLE Pitstops(
	RaceId INTEGER NOT NULL,
	DriverId INTEGER NOT NULL,
	Stop INTEGER NOT NULL,
	Lap INTEGER NOT NULL,
	Time VARCHAR(20) NOT NULL,
	Duration FLOAT NOT NULL,
	Milliseconds INTEGER NOT NULL,

	CONSTRAINT pk_pitstops PRIMARY KEY(RaceId, DriverId, Stop),
	CONSTRAINT fk_pitstops_race FOREIGN KEY(RaceId) REFERENCES Races(RaceId),
	CONSTRAINT fk_pitstops_driver FOREIGN KEY(DriverId) REFERENCES Driver(DriverId)
);

CREATE TABLE Qualifying(
	QualifyId INTEGER NOT NULL,
	RaceId INTEGER NOT NULL,
	DriverId INTEGER NOT NULL,
	ConstructorId INTEGER NOT NULL,
	Number INTEGER NOT NULL,
	Position INTEGER NOT NULL,
	Q1 VARCHAR(10) NOT NULL,
	Q2 VARCHAR(10) DEFAULT '\N',
	Q3 VARCHAR(10) DEFAULT '\N',

	CONSTRAINT pk_qualifying PRIMARY KEY(QualifyId),
	CONSTRAINT fk_qualifying_race FOREIGN KEY(RaceId) REFERENCES Races(RaceId),
	CONSTRAINT fk_qualifying_driver FOREIGN KEY(DriverId) REFERENCES Driver(DriverId),
	CONSTRAINT fk_qualifying_constructor FOREIGN KEY(ConstructorId) REFERENCES Constructors(ConstructorId)
);

CREATE TABLE DriverStandings(
	DriverStandingsId INTEGER NOT NULL,
	RaceID INTEGER NOT NULL,
	DriverId INTEGER NOT NULL,
	Points FLOAT NOT NULL,
	Position INTEGER NOT NULL,
	PositionText VARCHAR(3) NOT NULL,
	Win VARCHAR(3) NOT NULL,

	CONSTRAINT pk_driverstandings PRIMARY KEY(DriverStandingsId),
	CONSTRAINT fk_driverstandings_race FOREIGN KEY(RaceId) REFERENCES Races(RaceId),
	CONSTRAINT fk_driverstandings_driver FOREIGN KEY(DriverId) REFERENCES Driver(DriverId)
);

CREATE TABLE Results(
	ResultId INTEGER NOT NULL,
	RaceId INTEGER NOT NULL,
	DriverId INTEGER NOT NULL,
	ConstructorId INTEGER NOT NULL,
	Number VARCHAR(10) DEFAULT '\N' NOT NULL,
	Grid INTEGER NOT NULL,
	Position VARCHAR(3) DEFAULT '\N' NOT NULL,
	PositionText VARCHAR(3) DEFAULT 'R' NOT NULL,
	PositionOrder INTEGER NOT NULL,
	Points FLOAT NOT NULL,
	Laps INTEGER NOT NULL,
 	Time VARCHAR(20) DEFAULT '\N' NOT NULL,
 	Milliseconds VARCHAR(8) DEFAULT '\N' NOT NULL,
 	FastestLap VARCHAR(3) DEFAULT '\N' NOT NULL,
 	Rank VARCHAR(3) DEFAULT '\N' NOT NULL,
 	FastestLapTime VARCHAR(10) DEFAULT '\N' NOT NULL,
 	FastestLapSpeed VARCHAR(10) DEFAULT '\N' NOT NULL,
 	StatusID INTEGER NOT NULL,

	CONSTRAINT pk_results PRIMARY KEY(ResultId),
	CONSTRAINT fk_results_race FOREIGN KEY(RaceId) REFERENCES Races(RaceId),
	CONSTRAINT fk_results_driver FOREIGN KEY(DriverId) REFERENCES Driver(DriverId),
	CONSTRAINT fk_results_constructor FOREIGN KEY(ConstructorId) REFERENCES Constructors(ConstructorId),
	CONSTRAINT fk_results_status FOREIGN KEY(StatusId) REFERENCES Status(StatusId)
);
